<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * coursuploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coursuploadRepository extends EntityRepository
{
}
