services:
    login_success_handler:
            class: UserBundle\Handler\LoginSuccessHandler
            arguments:  [@router, @security.context]
            tags:
                - { name: 'monolog.logger', channel: 'security' }
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
